trigger: none

jobs:
- job: Terrafomrinitoplan
  displayName: Terraform init to plan
  pool: Avnesh_group
  steps:  
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'

  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 'Avnesh'
      backendAzureRmStorageAccountName: 'avstorage1'
      backendAzureRmContainerName: 'avcontainer1'
      backendAzureRmKey: 'av.tfstate'

   