trigger:
- main  
- frature101/*

jobs:
- job: Terrafomrinitoplan
  displayName: Terraform init to plan
  pool: Avnesh_group
  steps:  
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'

  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 'Avnesh'
      backendAzureRmStorageAccountName: 'avstorage1'
      backendAzureRmContainerName: 'avcontainer1'
      backendAzureRmKey: 'av.tfstate'
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'validate'


- job: manualvalidation
  pool: server
  steps:
  - task: ManualValidation@1
    inputs:
      notifyUsers: 'avneshkushwaha1289@gmail.com'
      approvers: 'avneshkushwaha1289@gmail.com'
      instructions: 'please approve'


- job: Terraformplan
  displayName: Terraform plan 
  pool: Avnesh_group
  steps:
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 'Avnesh'
      backendAzureRmStorageAccountName: 'avstorage1'
      backendAzureRmContainerName: 'avcontainer1'
      backendAzureRmKey: 'av.tfstate'
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'plan'
      environmentServiceNameAzureRM: 'Avnesh'